name: 'Build and Push Image'
on:
  workflow_dispatch:
    # inputs:
    #   image:
    #     type: choice
    #     description: 'Which component's image should be pushed'
    #     required: true
    #     options:
    #     - webapp
    #     - api
    inputs:
      test:
        type: boolean
        default: True
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set up Docker Buildx'
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: 'Login to Quay container registry'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: 'Build and push image'
        uses: docker/build-push-action@v3
        with:
          push: true
          # tags: quay.io/kklassa/k8s-demo-${{ inputs.image }}:latest
          # file: ${pwd}/demo-apps/demo-${{ inputs.image }}/Dockerfile
          tags: quay.io/kklassa/k8s-demo-api:latest
          file: demo-apps/demo-api/Dockerfile
