name: 'Build and Push Image'
on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: 'Which component's image should be pushed'
        required: true
        options:
          - webapp
          - api
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set up Docker Buildx'
        id: buildx
        uses: docker/setup-buildx-action@v2
      # - name: 'Choose component registry'
      #   id: registry
      #   run: |
      #     if [[ "${{ github.event.inputs.choice }}" == "webapp" ]]; then
      #       echo "Will push to ${{ github.event.inputs.choice }} registry."
      #       echo "::set-output name=component::webapp"
      #     elif [[ "${{ github.event.inputs.choice }}" == "api" ]]; then
      #       echo "Will push to ${{ github.event.inputs.choice }} registry."
      #       echo "::set-output name=component::api"
      #     fi
      - name: 'Login to Quay container registry'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: 'Build and push image'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: quay.io/kklassa/k8s-demo-${{ inputs.choice }}:latest
          file: ${pwd}/demo-apps/demo-${{ inputs.choice }}/Dockerfile
